application: anr-epitome
version: beta
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /(.*\.js)
  static_files: \1
  upload: (.*\.js)

- url: /.*
  script: epitome.app
